version: 2

sources:
  - name: raw
    database: lofty-psyche-475009-r5
    schema: gz_raw_data
    loader: bigquery
    description: this is the raw data
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
# --- New Ad Campaign Sources ---
      - name: adwords
        identifier: raw_gz_adwords
        description: Google Ads campaign performance data
        columns:
          - name: campaign_id
            description: unique identifier for each Google Ads campaign
          - name: clicks
            description: number of ad clicks
          - name: impressions
            description: number of ad impressions
          - name: spend
            description: total ad spend
          - name: date_date
            description: date of campaign performance record

      - name: bing
        identifier: raw_gz_bing
        description: Microsoft Bing Ads campaign performance data
        columns:
          - name: campaign_id
            description: unique identifier for each Bing Ads campaign
          - name: clicks
            description: number of ad clicks
          - name: impressions
            description: number of ad impressions
          - name: spend
            description: total ad spend
          - name: date_date
            description: date of campaign performance record

      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo retargeting campaign performance data
        columns:
          - name: campaign_id
            description: unique identifier for each Criteo campaign
          - name: clicks
            description: number of ad clicks
          - name: impressions
            description: number of ad impressions
          - name: spend
            description: total ad spend
          - name: date_date
            description: date of campaign performance record

      - name: facebook
        identifier: raw_gz_facebook
        description: Meta (Facebook/Instagram) campaign performance data
        columns:
          - name: campaign_id
            description: unique identifier for each Meta campaign
          - name: clicks
            description: number of ad clicks
          - name: impressions
            description: number of ad impressions
          - name: spend
            description: total ad spend
          - name: date_date
            description: date of campaign performance record
      - name: product
        identifier: raw_gz_product
        description: this is the product table for gz
        columns:
           - name: products_id
             description: unique identifier for each product
             tests: 
                - unique
                - not_null 
           - name: purchse_price
             description: price of product  

      - name: sales
        identifier: raw_gz_sales
        description: this is the sales table for gz
        tests:
         - unique:
             column_name: "(orders_id || '-' || pdt_id)"
        columns:
           - name: date_date
             description: date given
           - name: orders_id
             description: info for order
           - name: pdt_id
             description: info for product
           - name: revenue
             description: calculated turnover
           - name: quantity
             description: amount of products ordered
      - name: ship
        identifier: raw_gz_ship
        description: this is the ship table for gz
        columns:
           - name: orders_id
             description: info of order
             tests: 
               - unique
               - not_null 
           - name: shipping_fee
             description: cost of shipping fee
           - name: logcost
             description: cost of logging
           - name: ship_cost
             description: cost for transport 
models:
  - name: int_campaigns_day
    description: union of ad platforms aggregated by day
    columns:
      - name: date_date
        description: date of the aggregated campaign metrics
      - name: total_ads_cost
        description: total ad spend for the day (sum of ads_cost)
      - name: total_impressions
        description: total impressions for the day (sum of impression)
      - name: total_clicks
        description: total clicks for the day (sum of click)

  - name: int_campaigns
    description: union all of adwords, bing, criteo, facebook.
    tests:
      - unique:
          column_name: "(campaign_key || '-' || date_date)"
    columns:
      - name: campaign_name
        description: campaign name from all ad platforms
        tests:
          - not_null
      - name: paid_source
        description: ad platform the data came from (adwords, bing, criteo, facebook)
        tests:
          - not_null


  - name: int_sales_margin
    description: joining sales and product to obtain pruchase cost and margin calcs
    columns:
      - name: orders_id
        description: order_id
        tests:
          - not_null
      - name: products_id
        description: products_id
      - name: date_date
        description: date of order

  - name: int_orders_operational
    description: orders to ship for op costs
    columns:
      - name: date_date
        description: date of orders
        tests:
          - not_null

  - name: finance_days
    description: daily KPIs
    columns:
      - name: date_date
        description: date of orders
        tests:
          - unique
          - not_null
      - name: nb_transactions
        description: number of transactions
      - name: total_revenue
        description: total rev calc
      - name: avg_basket
        description: averaging basket size, revn/order_num
      - name: operational_margin
        description: operatingal margin
      - name: total_purchase_cost
        description: sum of purchase cost
      - name: total_ship_fee
        description: sum of ship_fee
      - name: total_log_cost
        description: sum of log_cost
      - name: total_quantity
        description: sum of quantity


