version: 2

sources:
  - name: raw
    database: lofty-psyche-475009-r5
    schema: gz_raw_data
    loader: bigquery
    description: this is the raw data
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    tables:
      - name: product
        description: this is the product table for gz
      - name: sales
        description: this is the sales table for gz
      - name: ship
        description: this is the ship table for gz
